trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
      Python36Windows:
        imageName: 'windows-2019'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python38Windows:
        imageName: 'windows-latest'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python39Windows:
        imageName: 'windows-latest'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      pip install -U -r requirements.txt
      python setup.py sdist
    displayName: 'Build sdist'

  - script: python -m mypy confection
    displayName: 'Run mypy'

  - task: DeleteFiles@1
    inputs:
      contents: 'confection'
    displayName: 'Delete source directory'

  - bash: |
      SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
      pip install dist/$SDIST
    displayName: 'Install from sdist'

  - script: python -m pytest --pyargs confection
    displayName: 'Run tests'

  - bash: |
      pip install hypothesis
      python -c "import confection; import hypothesis"
    displayName: 'Test for conflicts'
