[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:^.*Support for class-based `config` is deprecated, use ConfigDict instead.*:DeprecationWarning"
]
