[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E203", "E501", "E402", "E731"]

[tool.ruff.lint.isort]
known-first-party = ["confection"]

[tool.pyright]
include = ["confection"]
exclude = ["confection/tests"]
pythonVersion = "3.10"
